on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - name: Build WASM
        working-directory: belalang-playground
        run: nix develop --command wasm-pack build --release

      - name: Install Dependencies
        run: nix develop --command pnpm install --frozen-lockfile

      - name: Build Project
        run: nix develop --command pnpm build

      - name: publish to cloudflare pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: ${{ secrets.CF_PROJECT_NAME }}
          directory: dist
